import Head from 'next/head'
import Link from 'next/link'
import Footer from './components/structure/Footer.js'
import styles from '../styles/Home.module.scss'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>PlanIt2</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>
          Hello there...
        </h1>
        <h2>
          General Kenobi...
        </h2>
        <p>
          <Link href='/user/log-in'>
            <a>Log In</a>
          </Link>
        </p>
        <p>
          <Link href='/user/sign-up'>
            <a>Sign Up</a>
          </Link>
        </p>
        <p>
          <Link href='/user/profile'>
            <a>Profile</a>
          </Link>
        </p>
      </main>

      <Footer />
    </div>
  )
}
