import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout'

export default function Home () {
  return (
    <Layout home>
      <Head>
        <title>PlanIt2</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1>
          Hello there...
        </h1>
        <h2>
          General Kenobi...
        </h2>
        <p>
          <Link href='/user/profile'>
            <a>Profile</a>
          </Link>
        </p>
      </div>

    </Layout>
  )
}
